name: Kanal Listesi Guncelleyici

on:
  schedule:
    # Her saat başı çalışır
    - cron: '0 * * * *'
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gerekli Kütüphaneleri Kur
      run: |
        pip install cloudscraper

    - name: Guncelleme Kodunu Calistir
      run: |
        python main.py

    - name: Degisiklikleri GitHub'a Yukle
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Yeni klasörü ve içindeki m3u dosyasını takibe al
        git add playlist/
        # Eğer bir değişiklik varsa commit yap ve gönder
        git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Liste Guncelleme" && git push)
