name: IPTV Otomatik Guncelle

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir çalışır
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bagimliliklari Yukle
        run: pip install requests

      - name: Scripti Calistir
        run: python update_list.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          # Sadece değişiklik varsa commit yap (hata almamak için)
          git diff --quiet && git diff --staged --quiet || (git commit -m "Playlist Guncellendi: $(date)" && git push)
